development:
  access_key_id: AKIAJ7XPIYOSPDMFVLFA
  secret_access_key: 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
  bucket: dd-testing
production:
  access_key_id: AKIAJ7XPIYOSPDMFVLFA
  secret_access_key: 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
  bucket: dancedynamics-heroku
